// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI (migrate, db push, studio): use direct Neon URL, not the pooler.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});


